#!/bin/bash
# Strict DLP Chinese (SDC) generate release file checksum script
# Strict DLP Chinese (SDC) is a strict DLP based on the eMule Xtreme (official) version. SoftBan list in SDC includes the eMule VeryCD Mod and the easyMule (1) because of GPL-breaker, private network, community leecher and other behavior.
# 
# Contributions: SDC team
# 


# Get current location.
working_path=$(cd `dirname $0`; pwd)

# Generate checksum and write result as document.
echo "* Release checksum (SHA3-256):" > "result.txt"
echo "  * x86:" >> "result.txt"
echo -en "    * all-verycd: " >> "result.txt"
openssl dgst --sha3-256 "$working_path/binary/x86/all-verycd/antiLeech.dll.new" | awk '{print $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo -en "    * easymule: " >> "result.txt"
openssl dgst --sha3-256 "$working_path/binary/x86/easymule/antiLeech.dll.new" | awk '{print $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo -en "    * lite: " >> "result.txt"
openssl dgst --sha3-256 "$working_path/binary/x86/lite/antiLeech.dll.new" | awk '{print $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo -en "    * verycd-nickname: " >> "result.txt"
openssl dgst --sha3-256 "$working_path/binary/x86/verycd-nickname/antiLeech.dll.new" | awk '{print $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo -en "    * verycd-tag: " >> "result.txt"
openssl dgst --sha3-256 "$working_path/binary/x86/verycd-tag/antiLeech.dll.new" | awk '{print $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo "  * x64:" >> "result.txt"
echo -en "    * all-verycd: " >> "result.txt"
openssl dgst --sha3-256 "$working_path/binary/x64/all-verycd/antiLeechx64.dll.new" | awk '{print $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo -en "    * easymule: " >> "result.txt"
openssl dgst --sha3-256 "$working_path/binary/x64/easymule/antiLeechx64.dll.new" | awk '{print $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo -en "    * lite: " >> "result.txt"
openssl dgst --sha3-256 "$working_path/binary/x64/lite/antiLeechx64.dll.new" | awk '{print $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo -en "    * verycd-nickname: " >> "result.txt"
openssl dgst --sha3-256 "$working_path/binary/x64/verycd-nickname/antiLeechx64.dll.new" | awk '{print $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo -en "    * verycd-tag: " >> "result.txt"
openssl dgst --sha3-256 "$working_path/binary/x64/verycd-tag/antiLeechx64.dll.new" | awk '{print $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo "  * ARM:" >> "result.txt"
echo -en "    * all-verycd: " >> "result.txt"
openssl dgst --sha3-256 "$working_path/binary/arm/all-verycd/antiLeecharm.dll.new" | awk '{print $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo -en "    * easymule: " >> "result.txt"
openssl dgst --sha3-256 "$working_path/binary/arm/easymule/antiLeecharm.dll.new" | awk '{print $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo -en "    * lite: " >> "result.txt"
openssl dgst --sha3-256 "$working_path/binary/arm/lite/antiLeecharm.dll.new" | awk '{print $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo -en "    * verycd-nickname: " >> "result.txt"
openssl dgst --sha3-256 "$working_path/binary/arm/verycd-nickname/antiLeecharm.dll.new" | awk '{print $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo -en "    * verycd-tag: " >> "result.txt"
openssl dgst --sha3-256 "$working_path/binary/arm/verycd-tag/antiLeecharm.dll.new" | awk '{print $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo "  * ARM64:" >> "result.txt"
echo -en "    * all-verycd: " >> "result.txt"
openssl dgst --sha3-256 "$working_path/binary/arm64/all-verycd/antiLeecharm64.dll.new" | awk '{print $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo -en "    * easymule: " >> "result.txt"
openssl dgst --sha3-256 "$working_path/binary/arm64/easymule/antiLeecharm64.dll.new" | awk '{print $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo -en "    * lite: " >> "result.txt"
openssl dgst --sha3-256 "$working_path/binary/arm64/lite/antiLeecharm64.dll.new" | awk '{print $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo -en "    * verycd-nickname: " >> "result.txt"
openssl dgst --sha3-256 "$working_path/binary/arm64/verycd-nickname/antiLeecharm64.dll.new" | awk '{print $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo -en "    * verycd-tag: " >> "result.txt"
openssl dgst --sha3-256 "$working_path/binary/arm64/verycd-tag/antiLeecharm64.dll.new" | awk '{print $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo "  * ARM64EC:" >> "result.txt"
echo -en "    * all-verycd: " >> "result.txt"
openssl dgst --sha3-256 "$working_path/binary/arm64ec/all-verycd/antiLeecharm64ec.dll.new" | awk '{print $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo -en "    * easymule: " >> "result.txt"
openssl dgst --sha3-256 "$working_path/binary/arm64ec/easymule/antiLeecharm64ec.dll.new" | awk '{print $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo -en "    * lite: " >> "result.txt"
openssl dgst --sha3-256 "$working_path/binary/arm64ec/lite/antiLeecharm64ec.dll.new" | awk '{print $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo -en "    * verycd-nickname: " >> "result.txt"
openssl dgst --sha3-256 "$working_path/binary/arm64ec/verycd-nickname/antiLeecharm64ec.dll.new" | awk '{print $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo -en "    * verycd-tag: " >> "result.txt"
openssl dgst --sha3-256 "$working_path/binary/arm64ec/verycd-tag/antiLeecharm64ec.dll.new" | awk '{print $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo "* Release checksum (SHA2-256):" >> "result.txt"
echo "  * x86:" >> "result.txt"
echo -en "    * all-verycd: " >> "result.txt"
openssl dgst -sha256 "$working_path/binary/x86/all-verycd/antiLeech.dll.new" | awk '{print $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo -en "    * easymule: " >> "result.txt"
openssl dgst -sha256 "$working_path/binary/x86/easymule/antiLeech.dll.new" | awk '{print $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo -en "    * lite: " >> "result.txt"
openssl dgst -sha256 "$working_path/binary/x86/lite/antiLeech.dll.new" | awk '{print $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo -en "    * verycd-nickname: " >> "result.txt"
openssl dgst -sha256 "$working_path/binary/x86/verycd-nickname/antiLeech.dll.new" | awk '{print $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo -en "    * verycd-tag: " >> "result.txt"
openssl dgst -sha256 "$working_path/binary/x86/verycd-tag/antiLeech.dll.new" | awk '{print $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo "  * x64:" >> "result.txt"
echo -en "    * all-verycd: " >> "result.txt"
openssl dgst -sha256 "$working_path/binary/x64/all-verycd/antiLeechx64.dll.new" | awk '{print $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo -en "    * easymule: " >> "result.txt"
openssl dgst -sha256 "$working_path/binary/x64/easymule/antiLeechx64.dll.new" | awk '{print $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo -en "    * lite: " >> "result.txt"
openssl dgst -sha256 "$working_path/binary/x64/lite/antiLeechx64.dll.new" | awk '{print $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo -en "    * verycd-nickname: " >> "result.txt"
openssl dgst -sha256 "$working_path/binary/x64/verycd-nickname/antiLeechx64.dll.new" | awk '{print $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo -en "    * verycd-tag: " >> "result.txt"
openssl dgst -sha256 "$working_path/binary/x64/verycd-tag/antiLeechx64.dll.new" | awk '{print $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo "  * ARM:" >> "result.txt"
echo -en "    * all-verycd: " >> "result.txt"
openssl dgst -sha256 "$working_path/binary/arm/all-verycd/antiLeecharm.dll.new" | awk '{print $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo -en "    * easymule: " >> "result.txt"
openssl dgst -sha256 "$working_path/binary/arm/easymule/antiLeecharm.dll.new" | awk '{print $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo -en "    * lite: " >> "result.txt"
openssl dgst -sha256 "$working_path/binary/arm/lite/antiLeecharm.dll.new" | awk '{print $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo -en "    * verycd-nickname: " >> "result.txt"
openssl dgst -sha256 "$working_path/binary/arm/verycd-nickname/antiLeecharm.dll.new" | awk '{print $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo -en "    * verycd-tag: " >> "result.txt"
openssl dgst -sha256 "$working_path/binary/arm/verycd-tag/antiLeecharm.dll.new" | awk '{print $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo "  * ARM64:" >> "result.txt"
echo -en "    * all-verycd: " >> "result.txt"
openssl dgst -sha256 "$working_path/binary/arm64/all-verycd/antiLeecharm64.dll.new" | awk '{print $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo -en "    * easymule: " >> "result.txt"
openssl dgst -sha256 "$working_path/binary/arm64/easymule/antiLeecharm64.dll.new" | awk '{print $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo -en "    * lite: " >> "result.txt"
openssl dgst -sha256 "$working_path/binary/arm64/lite/antiLeecharm64.dll.new" | awk '{print $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo -en "    * verycd-nickname: " >> "result.txt"
openssl dgst -sha256 "$working_path/binary/arm64/verycd-nickname/antiLeecharm64.dll.new" | awk '{print $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo -en "    * verycd-tag: " >> "result.txt"
openssl dgst -sha256 "$working_path/binary/arm64/verycd-tag/antiLeecharm64.dll.new" | awk '{print $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo "  * ARM64EC:" >> "result.txt"
echo -en "    * all-verycd: " >> "result.txt"
openssl dgst -sha256 "$working_path/binary/arm64ec/all-verycd/antiLeecharm64ec.dll.new" | awk '{print $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo -en "    * easymule: " >> "result.txt"
openssl dgst -sha256 "$working_path/binary/arm64ec/easymule/antiLeecharm64ec.dll.new" | awk '{print $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo -en "    * lite: " >> "result.txt"
openssl dgst -sha256 "$working_path/binary/arm64ec/lite/antiLeecharm64ec.dll.new" | awk '{print $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo -en "    * verycd-nickname: " >> "result.txt"
openssl dgst -sha256 "$working_path/binary/arm64ec/verycd-nickname/antiLeecharm64ec.dll.new" | awk '{print $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo -en "    * verycd-tag: " >> "result.txt"
openssl dgst -sha256 "$working_path/binary/arm64ec/verycd-tag/antiLeecharm64ec.dll.new" | awk '{print $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo "" >> "result.txt"
echo "" >> "result.txt"

# Generate checksum and write result as markdown.
echo "Filename | SHA3-256 |" >> "result.txt"
echo ":--- | :--- |" >> "result.txt"
echo -en "x86/all-verycd | " >> "result.txt"
openssl dgst --sha3-256 "$working_path/binary/x86/all-verycd/antiLeech.dll.new" | awk '{printf $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo " |" >> "result.txt"
echo -en "x86/easymule | " >> "result.txt"
openssl dgst --sha3-256 "$working_path/binary/x86/easymule/antiLeech.dll.new" | awk '{printf $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo " |" >> "result.txt"
echo -en "x86/lite | " >> "result.txt"
openssl dgst --sha3-256 "$working_path/binary/x86/lite/antiLeech.dll.new" | awk '{printf $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo " |" >> "result.txt"
echo -en "x86/verycd-nickname | " >> "result.txt"
openssl dgst --sha3-256 "$working_path/binary/x86/verycd-nickname/antiLeech.dll.new" | awk '{printf $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo " |" >> "result.txt"
echo -en "x86/verycd-tag | " >> "result.txt"
openssl dgst --sha3-256 "$working_path/binary/x86/verycd-tag/antiLeech.dll.new" | awk '{printf $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo " |" >> "result.txt"
echo -en "x64/all-verycd | " >> "result.txt"
openssl dgst --sha3-256 "$working_path/binary/x64/all-verycd/antiLeechx64.dll.new" | awk '{printf $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo " |" >> "result.txt"
echo -en "x64/easymule | " >> "result.txt"
openssl dgst --sha3-256 "$working_path/binary/x64/easymule/antiLeechx64.dll.new" | awk '{printf $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo " |" >> "result.txt"
echo -en "x64/lite | " >> "result.txt"
openssl dgst --sha3-256 "$working_path/binary/x64/lite/antiLeechx64.dll.new" | awk '{printf $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo " |" >> "result.txt"
echo -en "x64/verycd-nickname | " >> "result.txt"
openssl dgst --sha3-256 "$working_path/binary/x64/verycd-nickname/antiLeechx64.dll.new" | awk '{printf $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo " |" >> "result.txt"
echo -en "x64/verycd-tag | " >> "result.txt"
openssl dgst --sha3-256 "$working_path/binary/x64/verycd-tag/antiLeechx64.dll.new" | awk '{printf $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo " |" >> "result.txt"
echo -en "arm/all-verycd | " >> "result.txt"
openssl dgst --sha3-256 "$working_path/binary/arm/all-verycd/antiLeecharm.dll.new" | awk '{printf $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo " |" >> "result.txt"
echo -en "arm/easymule | " >> "result.txt"
openssl dgst --sha3-256 "$working_path/binary/arm/easymule/antiLeecharm.dll.new" | awk '{printf $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo " |" >> "result.txt"
echo -en "arm/lite | " >> "result.txt"
openssl dgst --sha3-256 "$working_path/binary/arm/lite/antiLeecharm.dll.new" | awk '{printf $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo " |" >> "result.txt"
echo -en "arm/verycd-nickname | " >> "result.txt"
openssl dgst --sha3-256 "$working_path/binary/arm/verycd-nickname/antiLeecharm.dll.new" | awk '{printf $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo " |" >> "result.txt"
echo -en "arm/verycd-tag | " >> "result.txt"
openssl dgst --sha3-256 "$working_path/binary/arm/verycd-tag/antiLeecharm.dll.new" | awk '{printf $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo " |" >> "result.txt"
echo -en "arm64/all-verycd | " >> "result.txt"
openssl dgst --sha3-256 "$working_path/binary/arm64/all-verycd/antiLeecharm64.dll.new" | awk '{printf $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo " |" >> "result.txt"
echo -en "arm64/easymule | " >> "result.txt"
openssl dgst --sha3-256 "$working_path/binary/arm64/easymule/antiLeecharm64.dll.new" | awk '{printf $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo " |" >> "result.txt"
echo -en "arm64/lite | " >> "result.txt"
openssl dgst --sha3-256 "$working_path/binary/arm64/lite/antiLeecharm64.dll.new" | awk '{printf $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo " |" >> "result.txt"
echo -en "arm64/verycd-nickname | " >> "result.txt"
openssl dgst --sha3-256 "$working_path/binary/arm64/verycd-nickname/antiLeecharm64.dll.new" | awk '{printf $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo " |" >> "result.txt"
echo -en "arm64/verycd-tag | " >> "result.txt"
openssl dgst --sha3-256 "$working_path/binary/arm64/verycd-tag/antiLeecharm64.dll.new" | awk '{printf $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo " |" >> "result.txt"
echo -en "arm64ec/all-verycd | " >> "result.txt"
openssl dgst --sha3-256 "$working_path/binary/arm64ec/all-verycd/antiLeecharm64ec.dll.new" | awk '{printf $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo " |" >> "result.txt"
echo -en "arm64ec/easymule | " >> "result.txt"
openssl dgst --sha3-256 "$working_path/binary/arm64ec/easymule/antiLeecharm64ec.dll.new" | awk '{printf $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo " |" >> "result.txt"
echo -en "arm64ec/lite | " >> "result.txt"
openssl dgst --sha3-256 "$working_path/binary/arm64ec/lite/antiLeecharm64ec.dll.new" | awk '{printf $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo " |" >> "result.txt"
echo -en "arm64ec/verycd-nickname | " >> "result.txt"
openssl dgst --sha3-256 "$working_path/binary/arm64ec/verycd-nickname/antiLeecharm64ec.dll.new" | awk '{printf $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo " |" >> "result.txt"
echo -en "arm64ec/verycd-tag | " >> "result.txt"
openssl dgst --sha3-256 "$working_path/binary/arm64ec/verycd-tag/antiLeecharm64ec.dll.new" | awk '{printf $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo " |" >> "result.txt"
echo "" >> "result.txt"
echo "Filename | SHA2-256 | " >> "result.txt"
echo ":--- | :--- | " >> "result.txt"
echo -en "x86/all-verycd | " >> "result.txt"
openssl dgst -sha256 "$working_path/binary/x86/all-verycd/antiLeech.dll.new" | awk '{printf $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo " |" >> "result.txt"
echo -en "x86/easymule | " >> "result.txt"
openssl dgst -sha256 "$working_path/binary/x86/easymule/antiLeech.dll.new" | awk '{printf $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo " |" >> "result.txt"
echo -en "x86/lite | " >> "result.txt"
openssl dgst -sha256 "$working_path/binary/x86/lite/antiLeech.dll.new" | awk '{printf $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo " |" >> "result.txt"
echo -en "x86/verycd-nickname | " >> "result.txt"
openssl dgst -sha256 "$working_path/binary/x86/verycd-nickname/antiLeech.dll.new" | awk '{printf $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo " |" >> "result.txt"
echo -en "x86/verycd-tag | " >> "result.txt"
openssl dgst -sha256 "$working_path/binary/x86/verycd-tag/antiLeech.dll.new" | awk '{printf $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo " |" >> "result.txt"
echo -en "x64/all-verycd | " >> "result.txt"
openssl dgst -sha256 "$working_path/binary/x64/all-verycd/antiLeechx64.dll.new" | awk '{printf $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo " |" >> "result.txt"
echo -en "x64/easymule | " >> "result.txt"
openssl dgst -sha256 "$working_path/binary/x64/easymule/antiLeechx64.dll.new" | awk '{printf $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo " |" >> "result.txt"
echo -en "x64/lite | " >> "result.txt"
openssl dgst -sha256 "$working_path/binary/x64/lite/antiLeechx64.dll.new" | awk '{printf $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo " |" >> "result.txt"
echo -en "x64/verycd-nickname | " >> "result.txt"
openssl dgst -sha256 "$working_path/binary/x64/verycd-nickname/antiLeechx64.dll.new" | awk '{printf $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo " |" >> "result.txt"
echo -en "x64/verycd-tag | " >> "result.txt"
openssl dgst -sha256 "$working_path/binary/x64/verycd-tag/antiLeechx64.dll.new" | awk '{printf $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo " |" >> "result.txt"
echo -en "arm/all-verycd | " >> "result.txt"
openssl dgst -sha256 "$working_path/binary/arm/all-verycd/antiLeecharm.dll.new" | awk '{printf $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo " |" >> "result.txt"
echo -en "arm/easymule | " >> "result.txt"
openssl dgst -sha256 "$working_path/binary/arm/easymule/antiLeecharm.dll.new" | awk '{printf $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo " |" >> "result.txt"
echo -en "arm/lite | " >> "result.txt"
openssl dgst -sha256 "$working_path/binary/arm/lite/antiLeecharm.dll.new" | awk '{printf $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo " |" >> "result.txt"
echo -en "arm/verycd-nickname | " >> "result.txt"
openssl dgst -sha256 "$working_path/binary/arm/verycd-nickname/antiLeecharm.dll.new" | awk '{printf $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo " |" >> "result.txt"
echo -en "arm/verycd-tag | " >> "result.txt"
openssl dgst -sha256 "$working_path/binary/arm/verycd-tag/antiLeecharm.dll.new" | awk '{printf $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo " |" >> "result.txt"
echo -en "arm64/all-verycd | " >> "result.txt"
openssl dgst -sha256 "$working_path/binary/arm64/all-verycd/antiLeecharm64.dll.new" | awk '{printf $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo " |" >> "result.txt"
echo -en "arm64/easymule | " >> "result.txt"
openssl dgst -sha256 "$working_path/binary/arm64/easymule/antiLeecharm64.dll.new" | awk '{printf $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo " |" >> "result.txt"
echo -en "arm64/lite | " >> "result.txt"
openssl dgst -sha256 "$working_path/binary/arm64/lite/antiLeecharm64.dll.new" | awk '{printf $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo " |" >> "result.txt"
echo -en "arm64/verycd-nickname | " >> "result.txt"
openssl dgst -sha256 "$working_path/binary/arm64/verycd-nickname/antiLeecharm64.dll.new" | awk '{printf $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo " |" >> "result.txt"
echo -en "arm64/verycd-tag | " >> "result.txt"
openssl dgst -sha256 "$working_path/binary/arm64/verycd-tag/antiLeecharm64.dll.new" | awk '{printf $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo " |" >> "result.txt"
echo -en "arm64ec/all-verycd | " >> "result.txt"
openssl dgst -sha256 "$working_path/binary/arm64ec/all-verycd/antiLeecharm64ec.dll.new" | awk '{printf $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo " |" >> "result.txt"
echo -en "arm64ec/easymule | " >> "result.txt"
openssl dgst -sha256 "$working_path/binary/arm64ec/easymule/antiLeecharm64ec.dll.new" | awk '{printf $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo " |" >> "result.txt"
echo -en "arm64ec/lite | " >> "result.txt"
openssl dgst -sha256 "$working_path/binary/arm64ec/lite/antiLeecharm64ec.dll.new" | awk '{printf $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo " |" >> "result.txt"
echo -en "arm64ec/verycd-nickname | " >> "result.txt"
openssl dgst -sha256 "$working_path/binary/arm64ec/verycd-nickname/antiLeecharm64ec.dll.new" | awk '{printf $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo " |" >> "result.txt"
echo -en "arm64ec/verycd-tag | " >> "result.txt"
openssl dgst -sha256 "$working_path/binary/arm64ec/verycd-tag/antiLeecharm64ec.dll.new" | awk '{printf $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo " |" >> "result.txt"
