#!/bin/bash
# Strict DLP Chinese (SDC) release hash batch
# Strict DLP Chinese (SDC) is a strict DLP based on the eMule Xtreme (official) version. SoftBan list in SDC includes the eMule VeryCD Mod and the easyMule (1) because of GPL-breaker, private network, community leecher and other behavior.
# 
# Contributions: SDC team
# 


# Get current location.
working_path=$(cd `dirname $0`; pwd)

# Hash files and write result to readme documents.
echo "* Release Hash (SHA-3_256):" > "result.txt"
echo "  * x86:" >> "result.txt"
echo -en "    * All-VeryCD-Mod: " >> "result.txt"
openssl dgst --sha3-256 "$working_path/binary/x86/all-verycd-mod/antiLeech.dll.new" | awk '{print $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo -en "    * VeryCD-Tag: " >> "result.txt"
openssl dgst --sha3-256 "$working_path/binary/x86/verycd-tag/antiLeech.dll.new" | awk '{print $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo -en "    * Lite: " >> "result.txt"
openssl dgst --sha3-256 "$working_path/binary/x86/lite/antiLeech.dll.new" | awk '{print $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo -en "    * VeryCD-Default-NickNames: " >> "result.txt"
openssl dgst --sha3-256 "$working_path/binary/x86/verycd-default-nicknames/antiLeech.dll.new" | awk '{print $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo -en "    * VeryCD-EasyMule-Mod: " >> "result.txt"
openssl dgst --sha3-256 "$working_path/binary/x86/verycd-easymule-mod/antiLeech.dll.new" | awk '{print $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo "  * x64:" >> "result.txt"
echo -en "    * All-VeryCD-Mod: " >> "result.txt"
openssl dgst --sha3-256 "$working_path/binary/x64/all-verycd-mod/antiLeechx64.dll.new" | awk '{print $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo -en "    * VeryCD-Tag: " >> "result.txt"
openssl dgst --sha3-256 "$working_path/binary/x64/verycd-tag/antiLeechx64.dll.new" | awk '{print $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo -en "    * Lite: " >> "result.txt"
openssl dgst --sha3-256 "$working_path/binary/x64/lite/antiLeechx64.dll.new" | awk '{print $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo -en "    * VeryCD-Default-NickNames: " >> "result.txt"
openssl dgst --sha3-256 "$working_path/binary/x64/verycd-default-nicknames/antiLeechx64.dll.new" | awk '{print $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo -en "    * VeryCD-EasyMule-Mod: " >> "result.txt"
openssl dgst --sha3-256 "$working_path/binary/x64/verycd-easymule-mod/antiLeechx64.dll.new" | awk '{print $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo "  * ARM:" >> "result.txt"
echo -en "    * All-VeryCD-Mod: " >> "result.txt"
openssl dgst --sha3-256 "$working_path/binary/arm/all-verycd-mod/antiLeecharm.dll.new" | awk '{print $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo -en "    * VeryCD-Tag: " >> "result.txt"
openssl dgst --sha3-256 "$working_path/binary/arm/verycd-tag/antiLeecharm.dll.new" | awk '{print $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo -en "    * Lite: " >> "result.txt"
openssl dgst --sha3-256 "$working_path/binary/arm/lite/antiLeecharm.dll.new" | awk '{print $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo -en "    * VeryCD-Default-NickNames: " >> "result.txt"
openssl dgst --sha3-256 "$working_path/binary/arm/verycd-default-nicknames/antiLeecharm.dll.new" | awk '{print $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo -en "    * VeryCD-EasyMule-Mod: " >> "result.txt"
openssl dgst --sha3-256 "$working_path/binary/arm/verycd-easymule-mod/antiLeecharm.dll.new" | awk '{print $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo "  * ARM64:" >> "result.txt"
echo -en "    * All-VeryCD-Mod: " >> "result.txt"
openssl dgst --sha3-256 "$working_path/binary/arm64/all-verycd-mod/antiLeecharm64.dll.new" | awk '{print $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo -en "    * VeryCD-Tag: " >> "result.txt"
openssl dgst --sha3-256 "$working_path/binary/arm64/verycd-tag/antiLeecharm64.dll.new" | awk '{print $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo -en "    * Lite: " >> "result.txt"
openssl dgst --sha3-256 "$working_path/binary/arm64/lite/antiLeecharm64.dll.new" | awk '{print $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo -en "    * VeryCD-Default-NickNames: " >> "result.txt"
openssl dgst --sha3-256 "$working_path/binary/arm64/verycd-default-nicknames/antiLeecharm64.dll.new" | awk '{print $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo -en "    * VeryCD-EasyMule-Mod: " >> "result.txt"
openssl dgst --sha3-256 "$working_path/binary/arm64/verycd-easymule-mod/antiLeecharm64.dll.new" | awk '{print $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo "* Release Hash (SHA-2_256):" >> "result.txt"
echo "  * x86:" >> "result.txt"
echo -en "    * All-VeryCD-Mod: " >> "result.txt"
openssl dgst -sha256 "$working_path/binary/x86/all-verycd-mod/antiLeech.dll.new" | awk '{print $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo -en "    * VeryCD-Tag: " >> "result.txt"
openssl dgst -sha256 "$working_path/binary/x86/verycd-tag/antiLeech.dll.new" | awk '{print $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo -en "    * Lite: " >> "result.txt"
openssl dgst -sha256 "$working_path/binary/x86/lite/antiLeech.dll.new" | awk '{print $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo -en "    * VeryCD-Default-NickNames: " >> "result.txt"
openssl dgst -sha256 "$working_path/binary/x86/verycd-default-nicknames/antiLeech.dll.new" | awk '{print $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo -en "    * VeryCD-EasyMule-Mod: " >> "result.txt"
openssl dgst -sha256 "$working_path/binary/x86/verycd-easymule-mod/antiLeech.dll.new" | awk '{print $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo "  * x64:" >> "result.txt"
echo -en "    * All-VeryCD-Mod: " >> "result.txt"
openssl dgst -sha256 "$working_path/binary/x64/all-verycd-mod/antiLeechx64.dll.new" | awk '{print $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo -en "    * VeryCD-Tag: " >> "result.txt"
openssl dgst -sha256 "$working_path/binary/x64/verycd-tag/antiLeechx64.dll.new" | awk '{print $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo -en "    * Lite: " >> "result.txt"
openssl dgst -sha256 "$working_path/binary/x64/lite/antiLeechx64.dll.new" | awk '{print $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo -en "    * VeryCD-Default-NickNames: " >> "result.txt"
openssl dgst -sha256 "$working_path/binary/x64/verycd-default-nicknames/antiLeechx64.dll.new" | awk '{print $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo -en "    * VeryCD-EasyMule-Mod: " >> "result.txt"
openssl dgst -sha256 "$working_path/binary/x64/verycd-easymule-mod/antiLeechx64.dll.new" | awk '{print $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo "  * ARM:" >> "result.txt"
echo -en "    * All-VeryCD-Mod: " >> "result.txt"
openssl dgst -sha256 "$working_path/binary/arm/all-verycd-mod/antiLeecharm.dll.new" | awk '{print $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo -en "    * VeryCD-Tag: " >> "result.txt"
openssl dgst -sha256 "$working_path/binary/arm/verycd-tag/antiLeecharm.dll.new" | awk '{print $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo -en "    * Lite: " >> "result.txt"
openssl dgst -sha256 "$working_path/binary/arm/lite/antiLeecharm.dll.new" | awk '{print $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo -en "    * VeryCD-Default-NickNames: " >> "result.txt"
openssl dgst -sha256 "$working_path/binary/arm/verycd-default-nicknames/antiLeecharm.dll.new" | awk '{print $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo -en "    * VeryCD-EasyMule-Mod: " >> "result.txt"
openssl dgst -sha256 "$working_path/binary/arm/verycd-easymule-mod/antiLeecharm.dll.new" | awk '{print $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo "  * ARM64:" >> "result.txt"
echo -en "    * All-VeryCD-Mod: " >> "result.txt"
openssl dgst -sha256 "$working_path/binary/arm64/all-verycd-mod/antiLeecharm64.dll.new" | awk '{print $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo -en "    * VeryCD-Tag: " >> "result.txt"
openssl dgst -sha256 "$working_path/binary/arm64/verycd-tag/antiLeecharm64.dll.new" | awk '{print $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo -en "    * Lite: " >> "result.txt"
openssl dgst -sha256 "$working_path/binary/arm64/lite/antiLeecharm64.dll.new" | awk '{print $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo -en "    * VeryCD-Default-NickNames: " >> "result.txt"
openssl dgst -sha256 "$working_path/binary/arm64/verycd-default-nicknames/antiLeecharm64.dll.new" | awk '{print $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo -en "    * VeryCD-EasyMule-Mod: " >> "result.txt"
openssl dgst -sha256 "$working_path/binary/arm64/verycd-easymule-mod/antiLeecharm64.dll.new" | awk '{print $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo "" >> "result.txt"
echo "" >> "result.txt"


# Hash files and write result to git releases.
echo "Filename | SHA-3_256 | " >> "result.txt"
echo ":--- | :--- | " >> "result.txt"
echo -en "x86/All-VeryCD-Mod | " >> "result.txt"
openssl dgst --sha3-256 "$working_path/binary/x86/all-verycd-mod/antiLeech.dll.new" | awk '{printf $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo " | " >> "result.txt"
echo -en "x86/VeryCD-Tag | " >> "result.txt"
openssl dgst --sha3-256 "$working_path/binary/x86/verycd-tag/antiLeech.dll.new" | awk '{printf $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo " | " >> "result.txt"
echo -en "x86/Lite | " >> "result.txt"
openssl dgst --sha3-256 "$working_path/binary/x86/lite/antiLeech.dll.new" | awk '{printf $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo " | " >> "result.txt"
echo -en "x86/VeryCD-Default-NickNames | " >> "result.txt"
openssl dgst --sha3-256 "$working_path/binary/x86/verycd-default-nicknames/antiLeech.dll.new" | awk '{printf $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo " | " >> "result.txt"
echo -en "x86/VeryCD-EasyMule-Mod | " >> "result.txt"
openssl dgst --sha3-256 "$working_path/binary/x86/verycd-easymule-mod/antiLeech.dll.new" | awk '{printf $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo " | " >> "result.txt"
echo -en "x64/All-VeryCD-Mod | " >> "result.txt"
openssl dgst --sha3-256 "$working_path/binary/x64/all-verycd-mod/antiLeechx64.dll.new" | awk '{printf $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo " | " >> "result.txt"
echo -en "x64/VeryCD-Tag | " >> "result.txt"
openssl dgst --sha3-256 "$working_path/binary/x64/verycd-tag/antiLeechx64.dll.new" | awk '{printf $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo " | " >> "result.txt"
echo -en "x64/Lite | " >> "result.txt"
openssl dgst --sha3-256 "$working_path/binary/x64/lite/antiLeechx64.dll.new" | awk '{printf $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo " | " >> "result.txt"
echo -en "x64/VeryCD-Default-NickNames | " >> "result.txt"
openssl dgst --sha3-256 "$working_path/binary/x64/verycd-default-nicknames/antiLeechx64.dll.new" | awk '{printf $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo " | " >> "result.txt"
echo -en "x64/VeryCD-EasyMule-Mod | " >> "result.txt"
openssl dgst --sha3-256 "$working_path/binary/x64/verycd-easymule-mod/antiLeechx64.dll.new" | awk '{printf $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo " | " >> "result.txt"
echo ":--- | :--- | " >> "result.txt"
echo -en "arm/All-VeryCD-Mod | " >> "result.txt"
openssl dgst --sha3-256 "$working_path/binary/arm/all-verycd-mod/antiLeecharm.dll.new" | awk '{printf $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo " | " >> "result.txt"
echo -en "arm/VeryCD-Tag | " >> "result.txt"
openssl dgst --sha3-256 "$working_path/binary/arm/verycd-tag/antiLeecharm.dll.new" | awk '{printf $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo " | " >> "result.txt"
echo -en "arm/Lite | " >> "result.txt"
openssl dgst --sha3-256 "$working_path/binary/arm/lite/antiLeecharm.dll.new" | awk '{printf $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo " | " >> "result.txt"
echo -en "arm/VeryCD-Default-NickNames | " >> "result.txt"
openssl dgst --sha3-256 "$working_path/binary/arm/verycd-default-nicknames/antiLeecharm.dll.new" | awk '{printf $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo " | " >> "result.txt"
echo -en "arm/VeryCD-EasyMule-Mod | " >> "result.txt"
openssl dgst --sha3-256 "$working_path/binary/arm/verycd-easymule-mod/antiLeecharm.dll.new" | awk '{printf $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo " | " >> "result.txt"
echo -en "arm64/All-VeryCD-Mod | " >> "result.txt"
openssl dgst --sha3-256 "$working_path/binary/arm64/all-verycd-mod/antiLeecharm64.dll.new" | awk '{printf $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo " | " >> "result.txt"
echo -en "arm64/VeryCD-Tag | " >> "result.txt"
openssl dgst --sha3-256 "$working_path/binary/arm64/verycd-tag/antiLeecharm64.dll.new" | awk '{printf $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo " | " >> "result.txt"
echo -en "arm64/Lite | " >> "result.txt"
openssl dgst --sha3-256 "$working_path/binary/arm64/lite/antiLeecharm64.dll.new" | awk '{printf $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo " | " >> "result.txt"
echo -en "arm64/VeryCD-Default-NickNames | " >> "result.txt"
openssl dgst --sha3-256 "$working_path/binary/arm64/verycd-default-nicknames/antiLeecharm64.dll.new" | awk '{printf $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo " | " >> "result.txt"
echo -en "arm64/VeryCD-EasyMule-Mod | " >> "result.txt"
openssl dgst --sha3-256 "$working_path/binary/arm64/verycd-easymule-mod/antiLeecharm64.dll.new" | awk '{printf $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo " | " >> "result.txt"
echo "" >> "result.txt"
echo "Filename | SHA-2_256 | " >> "result.txt"
echo ":--- | :--- | " >> "result.txt"
echo -en "x86/All-VeryCD-Mod | " >> "result.txt"
openssl dgst -sha256 "$working_path/binary/x86/all-verycd-mod/antiLeech.dll.new" | awk '{printf $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo " | " >> "result.txt"
echo -en "x86/VeryCD-Tag | " >> "result.txt"
openssl dgst -sha256 "$working_path/binary/x86/verycd-tag/antiLeech.dll.new" | awk '{printf $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo " | " >> "result.txt"
echo -en "x86/Lite | " >> "result.txt"
openssl dgst -sha256 "$working_path/binary/x86/lite/antiLeech.dll.new" | awk '{printf $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo " | " >> "result.txt"
echo -en "x86/VeryCD-Default-NickNames | " >> "result.txt"
openssl dgst -sha256 "$working_path/binary/x86/verycd-default-nicknames/antiLeech.dll.new" | awk '{printf $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo " | " >> "result.txt"
echo -en "x86/VeryCD-EasyMule-Mod | " >> "result.txt"
openssl dgst -sha256 "$working_path/binary/x86/verycd-easymule-mod/antiLeech.dll.new" | awk '{printf $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo " | " >> "result.txt"
echo -en "x64/All-VeryCD-Mod | " >> "result.txt"
openssl dgst -sha256 "$working_path/binary/x64/all-verycd-mod/antiLeechx64.dll.new" | awk '{printf $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo " | " >> "result.txt"
echo -en "x64/VeryCD-Tag | " >> "result.txt"
openssl dgst -sha256 "$working_path/binary/x64/verycd-tag/antiLeechx64.dll.new" | awk '{printf $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo " | " >> "result.txt"
echo -en "x64/Lite | " >> "result.txt"
openssl dgst -sha256 "$working_path/binary/x64/lite/antiLeechx64.dll.new" | awk '{printf $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo " | " >> "result.txt"
echo -en "x64/VeryCD-Default-NickNames | " >> "result.txt"
openssl dgst -sha256 "$working_path/binary/x64/verycd-default-nicknames/antiLeechx64.dll.new" | awk '{printf $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo " | " >> "result.txt"
echo -en "x64/VeryCD-EasyMule-Mod | " >> "result.txt"
openssl dgst -sha256 "$working_path/binary/x64/verycd-easymule-mod/antiLeechx64.dll.new" | awk '{printf $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo " | " >> "result.txt"
echo -en "arm/All-VeryCD-Mod | " >> "result.txt"
openssl dgst -sha256 "$working_path/binary/arm/all-verycd-mod/antiLeecharm.dll.new" | awk '{printf $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo " | " >> "result.txt"
echo -en "arm/VeryCD-Tag | " >> "result.txt"
openssl dgst -sha256 "$working_path/binary/arm/verycd-tag/antiLeecharm.dll.new" | awk '{printf $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo " | " >> "result.txt"
echo -en "arm/Lite | " >> "result.txt"
openssl dgst -sha256 "$working_path/binary/arm/lite/antiLeecharm.dll.new" | awk '{printf $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo " | " >> "result.txt"
echo -en "arm/VeryCD-Default-NickNames | " >> "result.txt"
openssl dgst -sha256 "$working_path/binary/arm/verycd-default-nicknames/antiLeecharm.dll.new" | awk '{printf $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo " | " >> "result.txt"
echo -en "arm/VeryCD-EasyMule-Mod | " >> "result.txt"
openssl dgst -sha256 "$working_path/binary/arm/verycd-easymule-mod/antiLeecharm.dll.new" | awk '{printf $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo " | " >> "result.txt"
echo -en "arm64/All-VeryCD-Mod | " >> "result.txt"
openssl dgst -sha256 "$working_path/binary/arm64/all-verycd-mod/antiLeecharm64.dll.new" | awk '{printf $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo " | " >> "result.txt"
echo -en "arm64/VeryCD-Tag | " >> "result.txt"
openssl dgst -sha256 "$working_path/binary/arm64/verycd-tag/antiLeecharm64.dll.new" | awk '{printf $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo " | " >> "result.txt"
echo -en "arm64/Lite | " >> "result.txt"
openssl dgst -sha256 "$working_path/binary/arm64/lite/antiLeecharm64.dll.new" | awk '{printf $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo " | " >> "result.txt"
echo -en "arm64/VeryCD-Default-NickNames | " >> "result.txt"
openssl dgst -sha256 "$working_path/binary/arm64/verycd-default-nicknames/antiLeecharm64.dll.new" | awk '{printf $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo " | " >> "result.txt"
echo -en "arm64/VeryCD-EasyMule-Mod | " >> "result.txt"
openssl dgst -sha256 "$working_path/binary/arm64/verycd-easymule-mod/antiLeecharm64.dll.new" | awk '{printf $2}' | tr [:lower:] [:upper:] >> "result.txt"
echo " | " >> "result.txt"
